"""empty message

Revision ID: b955fcc85461
Revises: 
Create Date: 2020-08-30 22:42:55.475728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b955fcc85461'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('userTag', sa.String(length=200), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('mobile', sa.String(length=14), nullable=True),
    sa.Column('tweetCount', sa.Integer(), nullable=True),
    sa.Column('followingCount', sa.Integer(), nullable=True),
    sa.Column('followersCount', sa.Integer(), nullable=True),
    sa.Column('joined', sa.DateTime(), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(length=4294000000), nullable=True),
    sa.Column('profileImgUrl', sa.Text(length=42940000), nullable=True),
    sa.Column('posterImgUrl', sa.Text(length=42940000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('userTag')
    )
    op.create_table('followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parentId', sa.Integer(), nullable=False),
    sa.Column('follower', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parentId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tweets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(length=4294000000), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweetId', sa.Integer(), nullable=False),
    sa.Column('likedUserId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['likedUserId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tweetId'], ['tweets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('tweets')
    op.drop_table('followers')
    op.drop_table('users')
    # ### end Alembic commands ###
